version: '3.6'

services:
  frontend:
    image: "rubykube/mikroapp:0.1.5"
    volumes:
      - ../config/frontend/env.js:/home/node/public/env.js
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/;Host:www.app.local"
      traefik.port: 3000

  tower:
    build:
      context: "../vendor/tower"
    volumes:
      - ../config/frontend/tower.js:/home/app/env.js
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/tower;Host:www.app.local"
      traefik.port: 8080

